name: taskDatabricks
description: taskDatabricks

# Were we can define the inputs that our action will accept
inputs:
  ENVIRONMENT: 
    required: true
    description: "Environment"
  SUBSCRIPTIONID:
    required: true
    description: "Environment Parameters"
  AZURE_CREDENTIALS:
    required: true
    description: "Service Principal Credentials"


runs:
  using: "composite"

  steps:
  
    - name:                     Checkout
      uses:                     actions/checkout@v2

    - name:                     Azure Login - ${{ matrix.environments }}
      uses:                     azure/login@v1
      with:
        creds:                  ${{inputs.AZURE_CREDENTIALS}} 

      

