
name:                           onDeploy Databricks

on:                             
  workflow_dispatch:
jobs:
  ReuseableMatrixJobForDeployment:
    name: Master Deployment
    strategy:
      matrix:
        target: [ Sandbox, Development, UAT, Production ]
    uses: ./.github/workflows/taskDatabricks.yaml
    with:
      ENVIRONMENT: ${{ matrix.target }}
    secrets:
      ARM_CLIENT_ID:          ${{ secrets.ARM_CLIENT_ID }}    
      ARM_CLIENT_SECRET:      ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID:          ${{ secrets.ARM_TENANT_ID }}
      PAT_GITHUB:             ${{ secrets.PAT_GITHUB }}
  



      

  
  
