
name:                           onDeploy Databricks

on:                             
  workflow_dispatch:


jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: ciaran28/dstoolkit-mlops-databricks/.github/workflows/taskDatabricks.yaml@main
    with:
      target: ${{ matrix.target }}


  



      

  
  
