
name:                           master

on:                             [workflow_dispatch] 

jobs:
  merge:
    runs-on:                     ubuntu-latest
    environment:                 ${{ matrix.environments }}
    strategy:
        matrix:
          # Aligns To Environment Parameter File Names 
          environments:          [Development] 
    
    steps:
    
    # We need this because GitHub needs to clone the branch to pipeline
      - name:                     Checkout
        uses:                     actions/checkout@v2
      
      - name:                     Job_Create_Environments
        uses:                     "./MLOps_Engineer/1-DevOps_Pipeline_Layer/taskDatabricks" #Just need to pass the path from action
        # Defining the variables required in our action

        with:
          #version:                v1.0.0
          #namespace:              "stage"
          environment:            ${{ matrix.environments }}
          secrets:                ${{ secrets.Development}}
          #ARM_CLIENT_ID:          ${{ secrets.ARM_CLIENT_ID }}
          #ARM_CLIENT_SECRET:      ${{ secrets.ARM_CLIENT_SECRET }}
          #ARM_TENANT_ID:          ${{ secrets.ARM_TENANT_ID }}
  
  
