
name:                           master

on:                             [workflow_dispatch] 

jobs:
  merge:
    runs-on:                     ubuntu-latest
    environment:                 ${{ matrix.environments }}
    strategy:
        matrix:
          # Aligns To Environment Parameter File Names 
          environments:          [Development, UAT] 
    
    steps:
    
      #- name:                     Checkout
      #  uses:                     actions/checkout@v2
      
      - name:                     Job_Create_Environments
        uses:                     ".github/workflows/taskDatabricks.yaml"
        with:
          ENVIRONMENT:             ${{ matrix.environments }}
          SUBSCRIPTIONID:          ${{ secrets.SUBSCRIPTIONID}}
          AZURE_CREDENTIALS:       ${{ secrets.AZURE_CREDENTIALS}}

  
  
