name: taskDatabricks 
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string


# Were we can define the inputs that our action will accept

jobs:
  build:
    runs-on: ubuntu-latest
    environment:  ${{ matrix.target }}

    steps:      
      - name:                     Checkout
        uses:                     actions/checkout@v2

      - name:                     Azure Login - ${{ matrix.environments }}
        uses:                     azure/login@v1
        with:
          creds:                  ${{ secrets.AZURE_CREDENTIALS }} 

      - name:                     Deploy DBX CICD Azure Resources
        shell:                    bash
        run:                      ./MLOps_Engineer/1-DevOps_Pipeline_Layer/Utilities/Bash/utilsCreateAzureResources.sh
        env:
          ENVIRONMENT:            ${{ secrets.AZURE_CREDENTIALS }} 



