name: taskDatabricks 
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      AZURE_CREDENTIALS:
        required: false
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true


# Were we can define the inputs that our action will accept

jobs:
  build:
    name: ${{ inputs.ENVIRONMENT }} Environment Deployment
    runs-on: ubuntu-latest
    environment:  ${{ inputs.ENVIRONMENT }}


    steps:      
      - name:                     Checkout
        uses:                     actions/checkout@v2

      - shell: bash
        run: |
            echo Test1
            echo Test2
            echo Test3
        env:
          Test1: ${{ inputs.ENVIRONMENT }}
          Test2: ${{ inputs.AZURE_CREDENTIALS }}
          Test3: ${{ secrets.AZURE_CREDENTIALS }}

      - name:                     Azure Login - ${{ inputs.environments }}
        uses:                     azure/login@v1
        with:
          creds:                  ${{ secrets.AZURE_CREDENTIALS }} 

      - name:                     Deploy DBX CICD Azure Resources
        shell:                    bash
        run:                      ./MLOps_Engineer/1-DevOps_Pipeline_Layer/Utilities/Bash/utilsCreateAzureResources.sh
        env:
          ENVIRONMENT:            ${{ secrets.AZURE_CREDENTIALS }} 



